spring:
  application:
    version: 1.0.0-dev

  datasource:
    url: jdbc:postgresql://localhost:5432/typoteka
    username: typoteka_user
    password: 12345
    driver-class-name: org.postgresql.Driver